SELECT XMLELEMENT(NAME "Resultat", XMLAGG(XMLELEMENT(NAME "Bok", XMLATTRIBUTES(Title as "Titel"))))
FROM Book
WHERE ID IN(SELECT Book
			FROM EDITION
			GROUP BY Book
			HAVING XMLQUERY('count($TRANSLATIONS//)'
			)